/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicN8nCallbackRouteImport } from './routes/api/public/n8n-callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nCallbackRoute = ApiPublicN8nCallbackRouteImport.update({
  id: '/api/public/n8n-callback',
  path: '/api/public/n8n-callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/n8n-callback': typeof ApiPublicN8nCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/n8n-callback': typeof ApiPublicN8nCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/n8n-callback': typeof ApiPublicN8nCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/n8n-callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/n8n-callback'
  id: '__root__' | '/' | '/api/public/n8n-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicN8nCallbackRoute: typeof ApiPublicN8nCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n-callback': {
      id: '/api/public/n8n-callback'
      path: '/api/public/n8n-callback'
      fullPath: '/api/public/n8n-callback'
      preLoaderRoute: typeof ApiPublicN8nCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicN8nCallbackRoute: ApiPublicN8nCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
